### ISSUE TITLE
Unable to launch webdriverAgent because of xcodebuild fail xcodebuild with code 70

### ISSUE THREAD

**Issue by Sangitasubudhi** [isaacs/github#1751]
Xcode :11.3.1
os version :13.3.1
Appium:1.15.1

[XCUITest]     at quitAndUninstall (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/lib/driver.js:527:15)
[DevCon Factory] Releasing connections for 55641c3260ddf19af2d050f6f39e7c1042fde3f6 device on any port number
[DevCon Factory] Found cached connections to release: ["55641c3260ddf19af2d050f6f39e7c1042fde3f6:8100"]
[DevCon Factory] Releasing the listener for '55641c3260ddf19af2d050f6f39e7c1042fde3f6:8100'
[DevCon Factory] Cached connections count: 0
[XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[BaseDriver] Event 'newSessionStarted' logged at 1583398163818 (14:19:23 GMT+0530 (IST))
[W3C] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 70
[W3C] xcodebuild error message:
[W3C]
[W3C] 2020-03-05 14:18:53.426 xcodebuild[1166:51873]  iPhoneConnect: :iphone: unable to mount developer disk image, (Error Domain=com.apple.dtdevicekit Code=601 "Could not locate device support files." UserInfo={DeviceType=iPhone10,3, NSLocalizedDescription=Could not locate device support files., NSLocalizedRecoverySuggestion=This iPhone X (Model A1865, A1901, A1902, A1903) is running iOS 13.3.1 (17D50), which may not be supported by this version of Xcode.}) {
[W3C]     DeviceType = "iPhone10,3";
[W3C]     NSLocalizedDescription = "Could not locate device support files.";
[W3C]     NSLocalizedRecoverySuggestion = "This iPhone X (Model A1865, A1901, A1902, A1903) is running iOS 13.3.1 (17D50), which may not be supported by this version of Xcode.";
[W3C] }
[W3C] xcodebuild: error: Unable to find a destination matching the provided destination specifier:
[W3C] 		{ id:55641c3260ddf19af2d050f6f39e7c1042fde3f6 }
[W3C] 	The requested device could not be found because no available devices matched the request.
[W3C] 	Available destinations for the "WebDriverAgentRunner" scheme:
[W3C] 		{ platform:iOS, id:55641c3260ddf19af2d050f6f39e7c1042fde3f6, name:Skidata’S Iphone }
[W3C] 		{ platform:iOS Simulator, id:5792F22C-F696-438E-AE19-E8838FFBEF7D, OS:10.3.1, name:iPad (5th generation) }
[W3C] 		{ platform:iOS Simulator, id:814CC927-B5B8-4B61-AE7B-53172A309EF1, OS:11.1, name:iPad (5th generation) }
[W3C] 		{ platform:iOS Simulator, id:F24671EE-29DE-44CC-9012-19E6BE7A1837, OS:12.4, name:iPad (5th generation) }
[W3C] 		{ platform:iOS Simulator, id:F32CBF6E-1CBF-479B-BEE0-E80528E25796, OS:12.4, name:iPad (6th generation) }
[W3C] 		{ platform:iOS Simulator, id:6577FA39-541B-4E0C-8932-18A9C40D7829, OS:10.3.1, name:iPad Air }
[W3C] 		{ platform:iOS Simulator, id:C77606B4-4AD1-4DE4-93B0-26A794BBD698, OS:11.1, name:iPad Air }
[W3C] 		{ platform:iOS Simulator, id:EDAED0D6-17BD-4162-B97C-21BAA92FD3A0, OS:12.4, name:iPad Air }
[W3C] 		{ platform:iOS Simulator, id:F079872D-DBF4-4C33-BE7B-ABDEDD57C0B0, OS:12.4, name:iPad Air (3rd generation) }
[W3C] 		{ platform:iOS Simulator, id:D103B3BF-9634-41EE-98F7-BF171085928E, OS:10.3.1, name:iPad Air 2 }
[W3C] 		{ platform:iOS Simulator, id:C5A85972-9E5B-4A05-A67E-114CACFB57DB, OS:11.1, name:iPad Air 2 }
[W3C] 		{ platform:iOS Simulator, id:893AF2DB-F82E-440F-969B-26E7CF628540, OS:12.4, name:iPad Air 2 }
[W3C] 		{ platform:iOS Simulator, id:27250063-53DC-4D18-A39C-BBAFA146235F, OS:10.3.1, name:iPad Pro (9.7 inch) }
[W3C] 		{ platform:iOS Simulator, id:3335693A-090D-4C4F-8F07-0798A60FE29B, OS:11.1, name:iPad Pro (9.7-inch) }
[W3C] 		{ platform:iOS Simulator, id:1577CE3C-EC3E-47AD-BCAF-C40D641B6321, OS:12.4, name:iPad Pro (9.7-inch) }
[W3C] 		{ platform:iOS Simulator, id:8BF1D4A8-76E4-4AB7-BD7F-5C1DFBD6B2B6, OS:10.3.1, name:iPad Pro (10.5-inch) }
[W3C] 		{ platform:iOS Simulator, id:581E3901-303C-4F3C-B9F3-22BF79D0AF71, OS:11.1, name:iPad Pro (10.5-inch) }
[W3C] 		{ platform:iOS Simulator, id:49DCDD15-CA7B-4F3D-B020-823E604EB078, OS:12.4, name:iPad Pro (10.5-inch) }
[W3C] 		{ platform:iOS Simulator, id:A54FE366-9E30-4A95-876B-86425F9EF36B, OS:12.4, name:iPad Pro (11-inch) }
[W3C] 		{ platform:iOS Simulator, id:1BD4BA6D-E7BC-4A3C-BF31-2A4EEB021612, OS:10.3.1, name:iPad Pro (12.9 inch) }
[W3C] 		{ platform:iOS Simulator, id:6907456D-908B-4D50-BA8C-2BA91279748B, OS:11.1, name:iPad Pro (12.9-inch) }
[W3C] 		{ platform:iOS Simulator, id:F3DF5F75-E942-4E87-BAE6-AE5D3A9C2DB9, OS:12.4, name:iPad Pro (12.9-inch) }
[W3C] 		{ platform:iOS Simulator, id:743DB1AA-3A76-4B4D-81CF-0F44E8D72171, OS:10.3.1, name:iPad Pro (12.9-inch) (2nd generation) }
[W3C] 		{ platform:iOS Simulator, id:0AFDEACB-0283-4743-B6E0-0D0531C00C62, OS:11.1, name:iPad Pro (12.9-inch) (2nd generation) }
[W3C] 		{ platform:iOS Simulator, id:9C9BC367-7E5A-4594-8CB2-56F2F51DDCCD, OS:12.4, name:iPad Pro (12.9-inch) (2nd generation) }
[W3C] 		{ platform:iOS Simulator, id:D3249EE2-9E67-4F33-AA44-24A70DE66D2E, OS:12.4, name:iPad Pro (12.9-inch) (3rd generation) }
[W3C] 		{ platform:iOS Simulator, id:33EFC3AF-8DBC-4D66-9C13-A7CA45F0FDD9, OS:10.3.1, name:iPhone 5 }
[W3C] 		{ platform:iOS Simulator, id:998DBC4B-CD46-4D1F-A11E-77D3D81591E3, OS:10.3.1, name:iPhone 5s }
[W3C] 		{ platform:iOS Simulator, id:893C0A1F-DD9E-45D1-806A-7C353AB2AADE, OS:11.1, name:iPhone 5s }
[W3C] 		{ platform:iOS Simulator, id:4463E572-B46E-4E6F-900A-5F8BBB914181, OS:12.4, name:iPhone 5s }
[W3C] 		{ platform:iOS Simulator, id:21853619-498F-4853-9964-0CBC4503C79F, OS:10.3.1, name:iPhone 6 }
[W3C] 		{ platform:iOS Simulator, id:81655FD5-C860-4CEF-A5B4-68B1752F1847, OS:11.1, name:iPhone 6 }
[W3C] 		{ platform:iOS Simulator, id:4E8B2859-265B-4613-BEC5-1332CB0622B0, OS:12.4, name:iPhone 6 }
[W3C] 		{ platform:iOS Simulator, id:18CFF181-5C00-4E21-99EF-C2F2EDB03FFB, OS:10.3.1, name:iPhone 6 Plus }
[W3C] 		{ platform:iOS Simulator, id:133AD246-1C59-442E-80AE-B26E4D5DD4AE, OS:11.1, name:iPhone 6 Plus }
[W3C] 		{ platform:iOS Simulator, id:99F10F50-A6AE-41A1-95DF-DC051169B242, OS:12.4, name:iPhone 6 Plus }
[W3C] 		{ platform:iOS Simulator, id:0181AE87-8340-4AE2-A8CF-159A7758F463, OS:10.3.1, name:iPhone 6s }
[W3C] 		{ platform:iOS Simulator, id:9F67750E-40B3-4AD0-BAAE-936C4A0BD074, OS:11.1, name:iPhone 6s }
[W3C] 		{ platform:iOS Simulator, id:EC67A7F8-3D62-4201-BD44-FCF41AE3EEA6, OS:12.4, name:iPhone 6s }
[W3C] 		{ platform:iOS Simulator, id:614B9083-8AB9-40B0-9AC8-1FE54DAD34A2, OS:10.3.1, name:iPhone 6s Plus }
[W3C] 		{ platform:iOS Simulator, id:A34E50B8-F4E0-4AFD-A090-CF5C4B8E9A66, OS:11.1, name:iPhone 6s Plus }
[W3C] 		{ platform:iOS Simulator, id:CFBAF69B-DFDD-4F35-A111-3E0D8BB6D6C1, OS:12.4, name:iPhone 6s Plus }
[W3C] 		{ platform:iOS Simulator, id:8DC642FB-38A7-4CB4-B7E7-7E19135038E4, OS:10.3.1, name:iPhone 7 }
[W3C] 		{ platform:iOS Simulator, id:2C624922-EFE2-4C4A-A93D-56B3551A2C37, OS:11.1, name:iPhone 7 }
[W3C] 		{ platform:iOS Simulator, id:11DE8525-8BE7-41CF-9B96-A8D60FBF6F93, OS:12.4, name:iPhone 7 }
[W3C] 		{ platform:iOS Simulator, id:D4060F27-89A8-438B-9352-DC1BA0A64E82, OS:10.3.1, name:iPhone 7 Plus }
[W3C] 		{ platform:iOS Simulator, id:C3F29D53-5EE6-44E1-B2B8-927BF73E56BF, OS:11.1, name:iPhone 7 Plus }
[W3C] 		{ platform:iOS Simulator, id:816F3AFA-54D0-4098-8162-6B0B592984D9, OS:12.4, name:iPhone 7 Plus }
[W3C] 		{ platform:iOS Simulator, id:7E3A9551-39B4-45E6-989E-40AA8B589DAB, OS:11.1, name:iPhone 8 }
[W3C] 		{ platform:iOS Simulator, id:2D0CB699-657C-49D6-8F53-1612FF2243AF, OS:12.4, name:iPhone 8 }
[W3C] 		{ platform:iOS Simulator, id:95D92A35-4545-4BA1-AF99-7E4C17C6CD08, OS:11.1, name:iPhone 8 Plus }
[W3C] 		{ platform:iOS Simulator, id:9B8663BD-CD5B-460E-80C7-C9564552DA01, OS:12.4, name:iPhone 8 Plus }
[W3C] 		{ platform:iOS Simulator, id:5F3FC7EF-D5DA-4776-8EA2-9AFB136D9ABD, OS:10.3.1, name:iPhone SE }
[W3C] 		{ platform:iOS Simulator, id:94C5721E-D041-44F0-92AE-B6D84E2FEA8D, OS:11.1, name:iPhone SE }
[W3C] 		{ platform:iOS Simulator, id:12442AB8-D859-4446-ACC1-908D52911DF0, OS:12.4, name:iPhone SE }
[W3C] 		{ platform:iOS Simulator, id:C2FA9418-4FCD-4D7F-A89D-E1C08B5FA964, OS:11.1, name:iPhone X }
[W3C] 		{ platform:iOS Simulator, id:B3267EEC-6B5C-4012-9D09-EC5AFAC09256, OS:12.4, name:iPhone X }
[W3C] 		{ platform:iOS Simulator, id:46083D31-12B2-48DD-82DD-541173C4A940, OS:12.4, name:iPhone Xs }
[W3C] 		{ platform:iOS Simulator, id:F09BCC89-DF90-40F2-9B68-4C6A41422F79, OS:12.4, name:iPhone Xs Max }
[W3C] 		{ platform:iOS Simulator, id:01C8A21D-FB0A-4950-B1BA-D539325136FA, OS:12.4, name:iPhone Xʀ }
[W3C] 	Ineligible destinations for the "WebDriverAgentRunner" scheme:
[W3C] 		{ platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Generic iOS Device }
[W3C] 		{ platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Generic iOS Simulator Device }. Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
[W3C]     at quitAndUninstall (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/lib/driver.js:527:15)
[HTTP] <-- POST /wd/hub/session 500 81231 ms - 16764
[HTTP]

GitHubGitHub
appium/appium-xcuitest-driver
Appium iOS driver, backed by Apple XCUITest . Contribute to appium/appium-xcuitest-driver development by creating an account on GitHub.

**Comment by Sangitasubudhi** [comment]
Please help to resolve the issue
