### ISSUE TITLE
Original reporter should be able to reopen a closed issue

### ISSUE THREAD

**Issue by jmarshall** [isaacs/github#583]
Oftentimes we commit some fix in response to an issue, run our own tests, and close the issue with a comment along the lines of “We believe this has fixed the problem; please reopen if it still fails on your data”.

However it turns out that only organisation-members/contributors/people-with-write-access-to-repo/something-similar have the ability to reopen issues.  It would be useful if the user who originally opened the issue also had the ability to reopen their own issue, as they are also intimately concerned with whatever problem the issue is about.  If our fix has not been effective for their test case, they should be able to reopen the issue to signal this.

Maintainers / repo owners would probably need to have some control over this; e.g., using “Lock conversation” could also prevent third parties such as the original reporter from reopening the issue.

See for example the conversation in samtools/htslib#305 and samtools/htslib#306.  These are both the same underlying issue, but the reporter's inability to reopen his issue has lead to duplicate issues and more noise.

**Comment by jmarshall** [comment]
[Pretty run of the mill response from `support@github.com`, quoted in full with my replies interposed:]

> Thanks for sharing your idea with us, John -- I agree that might be useful in some situations. I'll pass your feedback to the team working on issues, but can't make any promises. Also, I'm not convinced this would really solve the duplicate issues problem. Sometimes the user who reported the issue isn't the one who wants to reopen it, but a different user, so those users would still open duplicates.

I think most often it is the original reporter who is particularly motivated to get their own problem fully resolved.

However you are right that sometimes others may want to reopen an existing issue.  Considering that everyone has access to the New Issue button, perhaps there is a case to be made that **anyone** should be able to reopen an existing (unlocked) issue -- if the alternative is that they will just use New Issue to create a duplicate.

Or perhaps "add a comment and OP/we'll reopen it" suffices for such people.

> For now, instead of asking users to "reopen the issue" if they can still reproduce the problem the reported, you could ask them "let us know in a comment if you can still reproduce the issue, and we'll reopen it". Would you be able to use such a workflow?

That would be a workaround, but it is more complicated and disempowers the users reporting issues.  So allowing the original reporter to actually reopen the issue would be a better experience for them, i.e., for people whom projects are presumably trying to encourage.

**Comment by hkdobrev** [comment]
I don't remember a time when this wasn't working. When I saw this issue I thought GitHub may have removed that recently. However here's a recent example of original creator re-opening the issue after has closed it: https://github.com/composer/composer/issues/4967#event-581410850 The issue creator is not a contributor to the repository.

I suspect that GitHub may have built it like so:
- If original issue creator closes the issue, they can then reopen it
- If a contributor closes the issue, the original issue creator is not able to reopen it

This workflow makes a lot of sense for me so maintainers can control the open state of their issues and when they mark something as a wontfix for example to be able to easily enforce it stay closed.

However if you think you want original issue creator to always be able to reopen an issue, please adjust the title and description of this issue.

**Comment by sbordet** [comment]
+1

Given that issues can be closed automagically with commit messages, the ability for the reporter to reopen the issue if the commit does not completely fix the issue is IMHO important.

Thanks !

**Comment by timotheecour** [comment]
+1
my number 1 issue with github issues.
Maintainer of a project closes an issue forcing me to reopen a duplicate issue, resulting in much noise and lost time.

**Comment by pcgeek86** [comment]
Yup I agree with @timotheecour -- it causes unnecessary noise

**Comment by lukehutch** [comment]
+1, I don't see the utility of denying a bug creator the ability to re-open their own bug by default.

The real question is how often this default behavior solves problems (e.g. preventing belligerent bug creators from re-opening their pet issue when a bug is marked as WAI) vs. how often it creates new problems (when a bug is closed too early, especially when bugs are closed automatically by a commit message). I would think the current behavior creates more problems than it solves.

**Comment by Karaulov** [comment]
+, Please add the possibility to reopen issue. (Issue can be not fixed and need create copy of issue ... Please add possible to reopen closed issue!)

**Comment by buhtz** [comment]
What is the status of thatIssue? Does someone work on implementing it?

**Comment by tekbasse** [comment]
Maybe change status from "closed" to "closed/disputed" or "open/ignored" ie something that shows the stat as closed to the developer, and yet differentiates closed/solved tickets from closed/disputed ones. This would be handy in helping to quickly assess the nature of developer support in some cases.

**Comment by mlewand** [comment]
> Maybe change status from "closed" to "closed/disputed" or "open/ignored" (...)

I think that adding new status names like that would bring unnecessary noise. I believe all we need here is a checkbox below "close" issue (or PR) button saying "allow reporter to reopen this issue" enabled by default.

That would be somewhat similar to "Allow edits from maintainers." checkbox when making the pull request.

**Comment by tekbasse** [comment]
@mlewand Yes, a single state Open/Closed is ideal in an ideal world. However, stackexchange and many open source bug trackers (as well as github) allow a ticket to be permanently closed to prevent "noise" from end-users etc re-opening a ticket that they conclude has been fixed. In these cases, an end user has the option to create a new ticket/issue. 

Allowing a ticket to remain closed and disputed/challenged, provides some indication to others that the issue is not resolved.  This can be done in such a way that the developer may continue to ignore the issue thread, while others may participate and/or collaborate on a solution (until re-closed by OP).  This also is helpful in providing analytics for assessing how well the developer handles issues overall.

**Comment by mlewand** [comment]
@tekbasse Sure, I understand what's your idea. My point was just to propose a simpler solution, similar to existing feature.

**Comment by errabelli09** [comment]
https://github.com/Alamofire/Alamofire/issues/2281

**Comment by kode54** [comment]
In this case, I want to re-open an issue I closed in one of my repositories, which was opened by someone else. Since they are not a contributor, they cannot re-open it themselves, and I cannot re-open it because it isn't my own issue.

**Comment by Tofandel** [comment]
This is definitely needed, this discussion has been ongoing for 2 years and a half, I see only one way.
It's pretty much unanimous and everyone is for it.
Why not be able to reopen an issue when you can recreate a new one anytime that is just loosing all the previous info ?..

**Comment by noMICROSOFTbuhtz** [comment]
Dear Microsoft don't waste your time anymore with this Issue. ;)

**Comment by sarpik** [comment]
+1

Just noticed that gitlab has this and it's super useful - I wish github could implement this too!

By the way, the `re-opened` status idea seems like a good fit!

**Comment by trivikr** [comment]
I sent the following email to GitHub support to check for update (if any)
Ticket ID: 251095

> Hi GitHub Staff,
>
> I would like to know status of this request https://github.com/isaacs/github/issues/583
> - It was opened couple of years ago
> - It has many likes, comments and references
> - Your competitor Gitlab has this feature.
>
> Is there a timeline to provide support for letting original reporter to open closed issues?

**Comment by trivikr** [comment]
Response from GitHub on Ticket ID 251095:
```
Hi Trivikram,

It doesn't look like we have any plans to move forward with this one in the near future I'm afraid. We periodically review our list of open requests, so there is a possibility we'll re-prioritise it at a later time.

Sorry we couldn't be of more help right now. If there's anything else we can do to assist, please let us know.

Cheers
GitHub Support
```

**Comment by jmarshall** [comment]
@trivikr: Disappointingly content-free response from GitHub.

What would be interesting would be an explanation of why on earth they think this is useful behaviour for a bug-tracking system.

**Comment by mayou36** [comment]
Given that a discussion can be locked _anyway_, I do not see a single use case for the current behavior. Can maybe anyone provide a _single_ usecase why the _original_ author (let's focus on the very simple case) cannot re-open an issue? (but create new issues, so if he wants to disturb, he still can)

**Comment by VNJoe** [comment]
Can we report the person that closed the case for Abuse?

**Comment by bcutter** [comment]
> 
> 
> Given that a discussion can be locked _anyway_, I do not see a single use case for the current behavior. Can maybe anyone provide a _single_ usecase why the _original_ author (let's focus on the very simple case) cannot re-open an issue? (but create new issues, so if he wants to make troubles, he still can)

Double that. Creates duplicates.

**Comment by mayou36** [comment]
Hi there, it's been quite some time and this issue seem from a technical point trivial to fix, from a logical point absolutely clear as well. What exactly is preventing this to proceed?

**Comment by agrawalarpit74** [comment]
with redisson-3.15.1 we are facing same error just at different line number.May be whole flow should be checked:
redisson version : 3.15.1
Error :An exception was thrown by org.redisson.misc.RedissonPromise$$Lambda$169/1201614274.operationComplete()

stack trace : 
java.lang.NullPointerException
	at org.redisson.connection.SentinelConnectionManager.lambda$null$4(SentinelConnectionManager.java:438)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at org.redisson.connection.SentinelConnectionManager.lambda$updateState$6(SentinelConnectionManager.java:446)
	at org.redisson.misc.RedissonPromise.lambda$onComplete$0(RedissonPromise.java:187)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)

**Comment by Shredder5262** [comment]
Perhaps not so much be able to re-open the issue as much as a mutual agreement that the issue can be closed along with some rational on why it is being closed . I would like it if i  (as a reporter) have a say on if the issue can be closed or not. Occasionally i will raise an issue with a project and it is simply dismissed without further question, or closed without resolution. Therefore, I as an end user am left with something that was broken, and i raised an issue for, is still broken. If I follow the process of raising an issue, it should lead to a resolution...not whatever the Dev decides is an issue and non-issue.
